### ISSUE TITLE
Include Windows Authentication Examples

### ISSUE THREAD

**Issue by danobri** [blowdart/AspNetAuthorizationWorkshop#21]
Would be great to see some examples included here that use windows authentication.  There doesn't seem to be a lot of information out there yet on how to handle custom authorization in an ASP.NET Core with windows authentication.  The best information I have found so far is your SO post:

[http://stackoverflow.com/a/40225551/432085]

**Comment by blowdart** [comment]
It won't, because this is authorization, not authentication. Customising Windows authentication isn't really what we're aiming at, with Windows the one true source of authentication, and roles, is AD/Windows. Adding onto that breaks that model I'm afraid.

**Comment by danobri** [comment]
Although I agree that when using Windows authentication it is ideal to do all authorization via the claims in the Windows identity, in my experience it's often necessary to augment the AD claims and roles with custom logic and data from your application.  

Ultimately I was able to to get a custom ClaimsTransformer working from information I found on the AspNet Security Github page.  I would be happy to share the complete code if you would like to include it in your samples.  Based on what I read in a number of GH and SO posts, I don't think I'm the only one that needs to augment AD claims.

**Comment by blowdart** [comment]
I think this might be better off as a PR in the [docs repo](https://github.com/aspnet/Docs), You'd also get your name up there :) If you just want to create it as an issue there, that'd work too, it'll go in the backlog.

**Comment by ferrx** [comment]
>It won't, because this is authorization, not authentication. Customising Windows authentication isn't really what we're aiming at, with Windows the one true source of authentication, and roles, is AD/Windows. Adding onto that breaks that model I'm afraid. @blowdart 

![shudder](https://canwehaveapooldad.files.wordpress.com/2015/08/02-18b-homershudder.gif)

@danobri Did you get a guide up somewhere?

**Comment by danobri** [comment]
No, but I did add the following post to the previously referenced SO question, that shows an example of how you can inject an EF DbContext into a customer ClaimsTransformer to augment AD claims.  The example is simple, but you could obviously put whatever logic necessary in the custom claims transformation.

[http://stackoverflow.com/a/43295616/432085](http://stackoverflow.com/a/43295616/432085)

Took me awhile to figure this out, so hope someone else will find it useful!

**Comment by ferrx** [comment]
@danobri Very similar to what I found. I ran into a solution in a pluralsight video (Identity and Access Control in ASP.Net 4.5) where they used [ClaimsAutheticationManager ](https://msdn.microsoft.com/en-us/library/system.security.claims.claimsauthenticationmanager%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) to transform their claims during the authetication pipeline. 

> Defines the base implementation for a claims authentication manager. The claims authentication manager provides a place in the claims processing pipeline for applying processing logic (filtering, validation, extension) to the claims collection in the incoming principal before execution reaches your application code.

> A typical reason for creating a custom claims authentication manager is to add, remove, or transform claims based on information that is only known by or is, perhaps, better maintained by the RP application. For example, a history of customer purchases in a shopping cart application might be kept in a data base maintained by the RP application and then added to the claims principal returned by the claims authentication manager based on the value of a name claim found in the incoming principal.

Basically the same idea, but I guess your answer fits more into an aspnet core solution.
