### ISSUE TITLE
Resource based authorisation broken in Core 2 branch

### ISSUE THREAD

**Issue by andrewlock** [blowdart/AspNetAuthorizationWorkshop#23]
I think that step 7 is broken in the core 2 branch - if you attempt to load Document 2, then you end up in an infinite redirect loop. I've only tested the core 2 branch using the preview 2 packages, but as far as I can see, this will be an issue on RTM too. 

I believe the issue is that the `ChallengeResult` is no longer (in 2.0) converted to a 403 response if you're already authenticated, so you end up in an infinite redirection loop in the `DocumentController.Edit` method:

```
public async Task<IActionResult> Edit(int id)
{
    var document = _documentRepository.Get(id);

    if (document == null)
    {
        return new NotFoundResult();
    }

    var authorizationResult = await _authorizationService.AuthorizeAsync(User, document, new EditRequirement());

    if (authorizationResult.Succeeded)
    {
        return View(document);
    }
    else
    {
        return new ChallengeResult(); // <-- if I'm already logged in, should return a 403
    }
}
```

I don't think this is a bug per se, but it's definitely a change in behaviour from 1.x and at the very least should be documented. I'm not entirely sure what the intended code should look like here.

Assuming that I'm not being an idiot (a big if), there only seems to be two options with the current behaviour: 

1. Inject an `IPolicyEvaluator`, call `AuthenticateAsync`, and `AuthorizeAsync` manually, as in the [`AuthorizeFilter`](https://github.com/aspnet/Mvc/blob/rel/2.0.0-preview2/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs).
2. Replace the line `return new ChallengeResult();` with

```
return User.Identity.IsAuthenticated
    ? (IActionResult) new ForbidResult()
    : new ChallengeResult();
```

The latter seems preferable, but it's still pretty gnarly (if it's even actually correct?). 

Thanks! 

P.S. As a fellow Brit, and knowing your feelings on bastardised spelling, I hope you enjoy the prevalence of 'ou' and lack of 'z' 😉

**Comment by blowdart** [comment]
@haok What's the right thing to do here?

**Comment by HaoK** [comment]
Yeah options 1, using the IPolicyEvaluator is the way to go, you might run into the same issue as here: https://github.com/aspnet/Security/issues/1341 where the policy evaluator has the side effect of manipulating the user.  You can work around that by caching the user, and then just stuffing it back after calling the evaluator.

**Comment by andrewlock** [comment]
Wow, really? That's a *lot* of work to do resource-based authorisation. You basically have to copy and paste the `AuthorizeFilter` into every action that does resource based auth?! 

Can you provide a code example, because everything I'm trying 
1. Is crazy amounts of work
2. Requires building a policy directly (can't use requirements only for resource-based auth), or injecting an `IPolicyProvider`,
3. Requires you to know the auth schemes when building the policy
4. Requires you to manually updates the `HttpContext.User` object.

 I guess something like this.

```c#
public class DocumentController : Controller
{
    IDocumentRepository _documentRepository;
    IAuthorizationService _authorizationService;
    IPolicyEvaluator _policyEvaluator;

    public DocumentController(IDocumentRepository documentRepository,
                                IPolicyEvaluator policyEvaluator,
                                IAuthorizationPolicyProvider policyProvider)
    {
        _documentRepository = documentRepository;
        _policyEvaluator = policyEvaluator;
    }

    public IActionResult Index()
    {
        return View(_documentRepository.Get());
    }

    public async Task<IActionResult> Edit(int id)
    {
        var document = _documentRepository.Get(id);

        if (document == null)
        {
            return new NotFoundResult();
        }

       // Everything below here to do resource-based auth?!
        var scheme = "SOMETHING?!";
        
        var effectivePolicy = new AuthorizationPolicy(new [] {new EditRequirement()}, new [] {scheme});
        var user = User;
        var authenticateResult = await _policyEvaluator.AuthenticateAsync(effectivePolicy, HttpContext);
        HttpContext.User = user;

        var authorizeResult = await _policyEvaluator.AuthorizeAsync(effectivePolicy, authenticateResult, HttpContext, document);

        if (authorizeResult.Challenged)
        {
            return new ChallengeResult(effectivePolicy.AuthenticationSchemes.ToArray());
        }
        else if (authorizeResult.Forbidden)
        {
            return new ForbidResult(effectivePolicy.AuthenticationSchemes.ToArray());
        }

        return View(document);
    }
}
```

That can't be right, surely? @HaoK are there any examples of this anywhere? I couldn't find any in any of the aspnet repos

**Comment by blowdart** [comment]
At the time of authorization I think we can assume that the user is authenticated (and I can make it clearer that this is the case by adding the authorize attribute.

If we all agree that's the case then the call to AuthenticateAsync at least goes away, and we return ForbidResult instead of Challenge, and we're back to where we were before.

This doesn't solve the case of adjusting views when someone is anonymous or authorized though :(

**Comment by andrewlock** [comment]
Yeah, that's fair enough in this case, but there still feels like there's a lot of issues, not least if you forget to add the `[Authorize]` attribute

To use the `IPolicyEvaluator` you still have the burden of having to manually create an `AuthenticateResult`  (if we're not calling `AuthenticateAsync()`) and not being able to provide a requirement directly using `new EditRequirement()`.

Instead, we're left having to inject and use an `IPolicyProvider` to find a policy by name, or by creating a new policy inline (as in the example above).

I'm sure it would easy enough to create a helper service for doing resource auth that wraps all this, it just seems odd that's not part of the framework I guess.

**Comment by andrewlock** [comment]
@HaoK That's good to here 😄 I can create an issue in the security repo if that's convenient. My concern is that I know you're locking down 2.0 RTM, but this feels like something that should definitely be in there!

**Comment by HaoK** [comment]
Almost certainly its going to have to wait until 2.1 now

**Comment by HaoK** [comment]
But yeah file the issue please :)

**Comment by blowdart** [comment]
Yea, if you go to step 7, it has a check to see if there's an authenticated user on the context, so it avoids this. You're right though, it's messy. At least we're rapidly iterating now, and you don't have to wait 2 years for the next version :)

**Comment by andrewlock** [comment]
Very true! :) I guess the question becomes, what's the specific advice (code sample) until 2.1 is released - because currently anyone who upgrades is going to have resource auth that leaves people stuck in a redirect loop!

**Comment by blowdart** [comment]
Yea :( That will needed documented in the breaking changes issue you have @HaoK.

I've updated the core2 branch now to reflect the changes.

**Comment by blowdart** [comment]
And to be fair to Hao here, the infinite loop is because the tutorial is lazy and just sets a principal automatically. If you had a login page like a sensible person you'd be almost ok, although you'd not get the forbidden you expected. Of course with Windows Auth it'd loop.

**Comment by andrewlock** [comment]
A good point - you just end up in a slow, infinite loop in which you have to login each time ;)

**Comment by andrewlock** [comment]
And also to be fair, if the fix is simply as you did - replace `ChallengeResult` with `ForbidResult` and add `[Authorize]` attribute - than that would bit fine for 99% of use cases I'm sure.

**Comment by blowdart** [comment]
OK as it's working, and it was my fault for returning ChallengeResult() I'm going to close this now :)
