### ISSUE TITLE
404 not 401 I think...

### ISSUE THREAD

**Issue by ehalsey** [blowdart/AspNetAuthorizationWorkshop#24]
On Step 1 Authorization 
Run the project and panic. You get a blank page. Open the IE Dev Tools, click Network then refresh the browser. **You will see you are getting a 401 returned**. The server is telling you that you are unauthorized.

At this step I'm getting a 302 to http://localhost:51396/Account/Login/?ReturnUrl=%2F and then 404 because Account/Login  hasn't been created at this point in the lab.

**Comment by Hoaas** [comment]
Same, not seeing a 401.
