### ISSUE TITLE
Any guidance for running this with EasyAuth in App Services?

### ISSUE THREAD

**Issue by markarnolditpro** [blowdart/AspNetAuthorizationWorkshop#34]
Should we expect this to run without changes in App Services with EasyAuth enabled?

**Comment by blowdart** [comment]
It shouldn't be different, except I believe they don't pass roles down from AAD, which kind of makes it just "Authenticated or unauthenticated" and you can't do anything else.

**Comment by blowdart** [comment]
You could yes, you'd just have to get data beyond the current username from somewhere else.
